### ISSUE TITLE
Build Docker image in CI

### ISSUE THREAD

**Issue by nykma** [NextDotID/core_service_sharp#2]
Should build Docker image for at least
- `linux/amd64`
- `linux/arm64`

I've implemented a draft version of this workflow.

Need further help to make it work.

Also docs for deploying this docker image should be added, if any.

**Comment by hmqgg** [comment]
Fixed via https://github.com/NextDotID/core_service_sharp/commit/0e21bfcd48fccc7b37025c152c69bfb59c8aacda
